max_steps = 1000
batch_size = 512
seq_len = 4096
rollouts_per_example = 8
mask_truncated_completions = false

[model]
name = "cosmicoptima/precursor-251125"
#name = "cosmicoptima/Prathamavatsa"

[wandb]
project = "introspection-bradley-terry"

[wandb.log_extras]
samples = true
distributions = true
interval = 2

[[env]]
id = "vf-bradley-terry"
[env.args]
model_name = "cosmicoptima/Prathamavatsa"

[sampling]
max_tokens = 1024

[ckpt]
interval = 200 