max_steps = 1000
batch_size = 512
micro_batch_size = 1
seq_len = 4096
rollouts_per_example = 8
mask_truncated_completions = false

[model]
# name = "cosmicoptima/GLM-4-32B-Base-32K"
name = "cosmicoptima/Prathamavatsa"

[wandb]
project = "introspection-bradley-terry"

[monitor.wandb.log_extras]
samples = true
distributions = true
interval = 2

[environment]
id = "vf-bradley-terry"

[sampling]
max_tokens = 1024

[ckpt]
interval = 200 