[project]
name = "reddit-user-grouping"
version = "1.0.0"
dependencies = [
    "scikit-learn>=1.7.1",
    "verifiers>=0.1.2.post0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_reddit_user_grouping.py"]
