max_steps = 120
batch_size = 256
seq_len = 2048
rollouts_per_example = 4
mask_truncated_completions = false

[model]
name = "cosmicoptima/Prathamavatsa"

[wandb]
project = "diksha"

[wandb.log_extras]
samples = true
distributions = true
interval = 2

[[env]]
id = "vf-llm-judge"
[env.args]
judge_model = "moonshotai/kimi-k2-0905:exacto"
judge_api_base = "https://openrouter.ai/api/v1"
openrouter_api_key_env = "OPENROUTER_API_KEY"
judge1_weight = 0.5
judge2_weight = 0.5

[sampling]
max_tokens = 1024

[ckpt]
interval = 10
