max_steps = 120

[wandb]
project = "diksha"

[model]
name = "cosmicoptima/Prathamavatsa"
impl = "liger_kernel"
reduce_dtype = "bfloat16"

[model.experimental.lora]
rank = 512
alpha = 1024.0
dropout = 0.05
target_modules = [
   ".*\\.q_proj$",
   ".*\\.k_proj$",
   ".*\\.v_proj$",
   ".*\\.o_proj$",
   ".*\\.gate_proj$",
   ".*\\.up_proj$",
   ".*\\.down_proj$",
]
modules_to_save = [
   "lm_head$",
   ".*\\.embed_tokens$",
   ".*\\.norm$",
]

[model.ac]
freq = 1

[optim]
lr = 3e-5
max_norm = 0.2
weight_decay = 0.001

[ckpt]
interval = 10
keep = 2

[weights]
interval = 10
save_format = "safetensors"
