max_steps = 100

[wandb]
project = "rigel-rl"

[model]
name = "cosmicoptima/Prathamavatsa"

[model.experimental.lora]
rank = 16
alpha = 256.0
dropout = 0.0
target_modules = [
   ".*\\.q_proj$",
   ".*\\.k_proj$",
   ".*\\.v_proj$",
   ".*\\.o_proj$",
   ".*\\.gate_up_proj$",
   ".*\\.down_proj$",
]
modules_to_save = []

[model.ac]
freq = 1

[optim]
lr = 5e-6
max_norm = 1.0

[ckpt]
interval = 50

[weights]
interval = 50
