max_steps = 500
batch_size = 1024
micro_batch_size = 2
seq_len = 4096
rollouts_per_example = 16
mask_truncated_completions = false

[model]
name = "Qwen/Qwen2.5-3B-Instruct"

[monitor.wandb]
project = "reddit-infilling"

[monitor.wandb.log_extras]
samples = true
distributions = true
interval = 2

[environment]
id = "reddit-infilling"

[sampling]
max_tokens = 832

[ckpt]
interval = 100