max_steps = 500

[monitor.wandb]
project = "reddit-infilling"

[model]
name = "Qwen/Qwen2.5-3B-Instruct"

[model.ac]
freq = 1

[optim]
lr = 1e-6
max_norm = 0.001
weight_decay = 0.001

[ckpt]
interval = 100