max_steps = 1000
batch_size = 512
#micro_batch_size = 1
seq_len = 4096
rollouts_per_example = 8
mask_truncated_completions = false

[model]
name = "cosmicoptima/sft-251116-safetensors"

[wandb]
project = "introspection-bradley-terry-judge-fmt"

[wandb.log_extras]
samples = true
distributions = true
interval = 2

[[env]]
id = "vf-bradley-terry-judge-fmt"

[env.args]
model_name = "cosmicoptima/Prathamavatsa"

[sampling]
max_tokens = 1024

[ckpt]
interval = 5
